// File generated by FlutterFire CLI.
// lib/firebase_options.dart
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzW6ANUnZ1C2qdf2ZQjiQT2Udhp6HFZF8',
    appId: '1:121039698129:web:d50908aab2437c4092adf0',
    messagingSenderId: '121039698129',
    projectId: 'routinetrackergame',
    authDomain: 'routinetrackergame.firebaseapp.com',
    storageBucket: 'routinetrackergame.firebasestorage.app',
    measurementId: 'G-9366CE66R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-juISXr7uawUJQSfgadOXWi59QRYEK20',
    appId: '1:121039698129:android:4d9ee7ac8641ce6692adf0',
    messagingSenderId: '121039698129',
    projectId: 'routinetrackergame',
    storageBucket: 'routinetrackergame.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzW6ANUnZ1C2qdf2ZQjiQT2Udhp6HFZF8',
    appId: '1:121039698129:web:75cd24424919e89892adf0',
    messagingSenderId: '121039698129',
    projectId: 'routinetrackergame',
    authDomain: 'routinetrackergame.firebaseapp.com',
    storageBucket: 'routinetrackergame.firebasestorage.app',
    measurementId: 'G-4RXNQZWJLD',
  );
}
